import { getClassNames } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
  authenticated,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
  authenticated: React.ReactNode;
}) {
  console.log({ auth, children, authenticated });

  return (
    <html lang='en' className='dark'>
      <body
        className={getClassNames(inter.className, 'bg-white dark:bg-black-100')}
      >
        {children}
      </body>
    </html>
  );
}
